Remove dead code and update settings.json
microsoft/vscode-jupyter pull request #14738
Opened 2023-11-19 23:33 UTC by DonJayamanne

2023-11-20 23:03 UTC, rzhao271 commented on .vscode/settings.json
> +    "workbench.colorCustomizations": {
Should these be user settings instead?

2023-11-20 23:03 UTC, rzhao271 requested changes
Requesting changes because the workbench.colorCustomizations change looks off to me.

2023-11-20 23:52 UTC, DonJayamanne commented on .vscode/settings.json
> +    "workbench.colorCustomizations": {
Nope, these can be here.

2023-11-21 00:16 UTC, rzhao271 approved these changes

2023-11-21 00:39 UTC, merged