Interactive window should use `IKernel.executeCell`
microsoft/vscode-jupyter pull request #7067
Opened 2021-08-11 16:01 UTC by joyceerhl

This PR fixes https://github.com/microsoft/vscode-jupyter/issues/6983

2021-08-11 16:13 UTC, rchiodo approved these changes

2021-08-11 16:19 UTC, DavidKutu approved these changes

2021-08-11 16:34 UTC, DonJayamanne commented on src/client/datascience/types.ts
> +    onBeforeCellExecute(notebookCell: NotebookCell): Promise<void>;
I'd rename this to `addCellHash` or something.
We know why we're calling this method, its to generate a hash. Hvaing a method named `onBeforeCellExecute` means its just an event handler & we have no idea what its doing.

I.e. i'd prefer us to be more explicit about the action we're performing. Else this is similar to a logger, kind of a black box, but that's not the case (i.e. we know what this class is meant to be used for).

2021-08-11 16:35 UTC, DonJayamanne requested changes
Please rename the method.

2021-08-12 02:31 UTC, DonJayamanne approved these changes

2021-08-13 15:17 UTC, merged