Replace Buffer constructors with safer methods
microsoft/vscode-jupyter pull request #9589
Opened 2022-04-05 01:55 UTC by caphosra

Fixes #9562.

-   [x] Pull request represents a single change (i.e. not fixing disparate/unrelated things in a single PR).
-   [x] Title summarizes what is changing.
-   [ ] Has a [news entry](https://github.com/Microsoft/vscode-jupyter/tree/main/news) file (remember to thank yourself!).
-   [ ] Appropriate comments and documentation strings in the code.
-   [ ] Has sufficient logging.
-   [ ] Has telemetry for enhancements.
-   [ ] Unit tests & system/integration tests are added/updated.
-   [ ] [Test plan](https://github.com/Microsoft/vscode-jupyter/blob/main/.github/test_plan.md) is updated as appropriate.
-   [ ] [`package-lock.json`](https://github.com/Microsoft/vscode-jupyter/blob/main/package-lock.json) has been regenerated by running `npm install` (if dependencies have changed).

2022-04-05 16:03 UTC, rchiodo approved these changes

2022-04-05 16:21 UTC, rchiodo requested changes
We should add a news entry file, something like so:
https://github.com/microsoft/vscode-jupyter/blob/82f3e416ce647faf974afd797c45cab4259bf0e2/news/2%20Fixes/9037.md

2022-04-06 04:05 UTC, caphosra commented
Ok, I add a news entry file. It should be valid.

2022-04-06 15:47 UTC, rchiodo approved these changes

2022-04-06 18:04 UTC, amunger approved these changes

2022-04-06 18:11 UTC, merged